# Generated by Django 2.2.28 on 2022-11-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_valid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
