# Generated by Django 2.2.28 on 2022-11-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_albuminventory_number_of_tracks'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEWmodule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.GenericIPAddressField()),
            ],
        ),
    ]
