# Generated by Django 2.2.28 on 2022-11-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221111_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newapp',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
